version: "3.9"
services:
  python-analysis:
    build: .
    restart:
      always
    container_name:
      python-analysis
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - .:/workspace
